Show run-bench help when run without arguments

diff --git a/scripts/run-bench b/scripts/run-bench
--- a/scripts/run-bench
+++ b/scripts/run-bench
@@ -34,7 +34,13 @@ function set_gpu_vars() {
 }
 
 # Parse les options de la ligne de commande
-action="$1"; shift
+if (($# < 1)); then
+    action="$1"; shift
+else
+    printf "Error: you must specify an action\n" >&2
+    show_help
+    exit
+fi
 
 while (($# > 0)); do
     opt="$1"; shift
